"""Reads a hosts file generated by https://github.com/StevenBlack/hosts.git.
Converts from /etc/hosts format to a Lua script for use by PowerDNS Recursor."""
import sys
import os.path

if len(sys.argv) == 1:
    print("must specify the hosts file to use")
    exit(1)

hosts_file_path = os.path.abspath(sys.argv[1])
hosts = []

print("Reading hosts from", hosts_file_path)

with open(hosts_file_path) as hosts_file:
    for line in hosts_file:
        line = line.strip()

        # skip blank lines & comments
        if not line:
            continue
        if line[0] == '#':
            continue

        # assume "ip address{space}hostname"
        host_start = line.find(' ') + 1
        host_end = line.find(' ', host_start)

        # ensure no extra comments
        if host_end == -1:
            host = line[host_start:]
        else:
            host = line[host_start:host_end]

        hosts.append('"' + host + '",')

if not hosts:
    raise ValueError("no hosts found in ")

lua_start = """-- modified from https://blog.spans.fi/2020/11/15/i-thought-pihole-was-kinda-bad-so-i-made-my-own.html
blackhole = newDS()
blackhole:add{
  """

lua_end = """ 
}

function preresolve(q)
  handled = false

  if blackhole:check(q.qname) then
    -- blackhole the host by returning the 0 address

    -- pdnslog("blackhole for "..q.qname:toString())

    if q.qtype==pdns.A then
      q:addAnswer(pdns.A, "0.0.0.0")
      handled = true
    end
    if q.qtype==pdns.AAAA then
      q:addAnswer(pdns.AAAA, "::")
      handled = true
    end
  end

  return handled
end
"""

# -1 to remove trailing ,
lua = lua_start + "\n  ".join(hosts)[:-1] + lua_end

lua_path = os.path.join(os.path.dirname(hosts_file_path), "blackhole.lua")

with open(lua_path, "w") as output:
    output.write(lua)

print("Wrote", len(hosts), "hosts to", lua_path)
