#!/bin/sh
# see https://www.libvirt.org/hooks.html
# expecting command line args like 'guest_name started begin -'

if [ "$2" = "started" ]; then
  # disable ipv6 when vswitch ports are created (i.e. vms are started)
  # domain xml is passed via stdin; parse for interface target device
  # assume libvirt device == Linux interface name
  for iface in $(xmlstarlet sel -T -t -m "/domain/devices/interface/target" -v "@dev" -n); do
    echo $iface
    sysctl -w net.ipv6.conf.$iface.disable_ipv6=1
    sysctl -w net.ipv6.conf.$iface.accept_ra=0
    sysctl -w net.ipv6.conf.$iface.autoconf=0
  done
fi
