domain: yodeler.internal
external_ntp:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  - 2.us.pool.ntp.org
  - 3.us.pool.ntp.org
timezone: US/Eastern
motd: Welcome to Yodeler's Standard Example Site!
alpine_repositories:
  - http://dl-cdn.alpinelinux.org/alpine/edge/main
  - http://dl-cdn.alpinelinux.org/alpine/edge/community
  - http://dl-cdn.alpinelinux.org/alpine/edge/testing
site_enable_metrics: false
public_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC9Av51+kAxf3Tozo/TueBDN3rWEcLWrTUjh672JpQGUAu71IzHBCxi4R6mZNi3+Z9HA4Ur2CeQWFZO1ZTZKwstJibaLh7SFoU1EggH9b0GNHPV35xVY+P2k0WNMXuKrKAAPeSL0kNh0TnTqF4qOX/rHwdORNvwXy4izLKFFH5uPQ== yodeler
# private key installed on any host that has 'install_private_ssh_key: true'
# DO NOT allow this host to have unrestricted internet access
private_ssh_key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAIEAvQL+dfpAMX906M6P07ngQzd61hHC1q01I4eu9iaUBlALu9SMxwQs
  YuEepmTYt/mfRwOFK9gnkFhWTtWU2SsLLSYm2i4e0haFNRIIB/W9BjRz1d+cVWPj9pNFjT
  F7iqygAD3ki9JDYdE506heKjl/6x8HTkTb8F8uIsyyhRR+bj0AAAIIeZHyEnmR8hIAAAAH
  c3NoLXJzYQAAAIEAvQL+dfpAMX906M6P07ngQzd61hHC1q01I4eu9iaUBlALu9SMxwQsYu
  EepmTYt/mfRwOFK9gnkFhWTtWU2SsLLSYm2i4e0haFNRIIB/W9BjRz1d+cVWPj9pNFjTF7
  iqygAD3ki9JDYdE506heKjl/6x8HTkTb8F8uIsyyhRR+bj0AAAADAQABAAAAgCAlRDW4a/
  Z/INj/WIK/2B5WbzO9LY/pQWJbjywZ/47bSkOVsKOgWBQxCU9vU1RmxeoD9UAxsPjhrTwX
  IwuUQIAQOtThTSEcdFwYgj0mHEr+CBozJggunsZ/5XXrc7ovp1O4Hxs2w89rg0yv2sY/rZ
  ucZugJnRiBVBCj0xT4LxIBAAAAQQCov165S7bSHIeDoviC34r7iN8DNAwrxzhr+/qr2B1Q
  +phaCwcs5T3HyY8p3MYxCOKNq9Dzz3xeKL5ZH6otCls1AAAAQQDsYKrQmrdtdhsOe786BL
  sSNtQCyQN4wy/jDn/LgBNrTjE7nyX5f3NVcOweX+S8NGQ4qDe4l+O5NXkR7ZzdH5rBAAAA
  QQDMs71CABNGN6Z3KR3eADQcyvGG1BIBwJtbAU/M7rQ545+GIjnvY17P4GtBnGFFKjGklF
  0MH/yy6YFDQC4xfV59AAAADkh1bnRlckBQbGFuY2hhAQIDBA==
  -----END OPENSSH PRIVATE KEY-----
vswitches:
  # switch shared by clients & servers which are in separate vlans
  # the router VM will allow routing between the vlans
  - name: public
    # add uplink here to allow other, physical systems access to these vlans
    # this uplink should connect to a switch port that trunks vlans 10 & 20
    vlans:
      - name: server
        id: 10
        domain: server.yodeler.internal
        ipv4_subnet: 192.168.210.0/24
        ipv6_subnet: fd24:87e8:06c7:10::/64
        # instead of defaulting to index order, set delegated prefix to the 10th /64 in the IPv6 PD
        # assumes 'ipv6_pd_prefixlen' of 56 defined in the router uplink
        ipv6_pd_network: 10
        dhcp4_enabled: false # DHCP server will not be configured
        # firewall will allow any access to all vlans, including the internet
        # can also set allow_internet: true to only allow some vlans + the internet
        access_vlans: all
        allow_dns_update: true # allow this subnet to make DDNS updates
      - name: client
        id: 20
        domain: client.yodeler.internal
        ipv4_subnet: 192.168.220.0/24
        ipv6_subnet: fd24:87e8:06c7:20::/64
        ipv6_pd_network: 20
        default: true # if not specified, VMs default to this vlan
        dhcp_min_address_ipv4: 16
        dhcp_max_address_ipv4: 128
        # dhcp6_managed defaults to false so DHCP6 will be information only
        # allow unrescricted access to the internet, supercedes later firewall rules
        # allow_internet: true
        allow_internet: true
        dhcp_reservations:
          - hostname: laptop
            ipv4_address: 192.168.220.24
            ipv6_address: fd24:87e8:06c7:20::18
            mac_address: ab:cd:ef:12:34:56 # will add static DHCP assignment
        # static_hosts: # for systems with staticly assigned IPs, not controlled by Yodeler
        #   - hostname: appliance
        #     ipv4_address: 192.168.220.101
        #     # optional ipv6_address
  # switch for "management" connections like physical switches, wireless access points, etc
  # the uplink is the port on the _vmhost_; this port is set as the uplink by open vswitch
  # for security, the router VM will not be on the management network
  - name: private
    # the physical port on the vmhost should either connect to a separate switch
    # or a vlan tagged port on the switch shared with the client & server vlans
    uplink: eth1
    vlans:
      - name: mgmt
        # default and only vlan
        # id is left as null; vswitch will not vlan tag
        routable: false # no interface and no firewall rules will be created on the router
        domain: mgmt.yodeler.internal
        ipv4_subnet: 172.16.251.0/24
        ipv6_disabled: true
        dhcp_min_address_ipv4: 2
        dhcp_max_address_ipv4: 16
firewall:
  # optionally add 'ipsets'
  # ipsets: # must be homogenous: all subnets or all address, all of the same IP version
  #   - name: other
  #     addresses: [10.10.10.0/24, 10.20.0.0/16]
  rules:
    - comment: all vlans have basic internet access
      # source and destination can also be plural and a list of locations
      # multiple values will be multiplexed into a rule for each source / destination combo
      source:
        vlan: all # source vlan name; 'all' for all routable networks; 'internet' for outbound
      destination:
        vlan: internet
      allow:
        # named services ...
        - web
        - ping
        - ntp
        # or, proto / port combinations
        # 'port' or 'ports' can be a single value or an array
        # values can be a single (integer) port or a string range
        - { proto: udp, port: 443, comment: Google QUIC } #
        - { proto: tcp, ports: "8000:8999", comment: faux HTTP ports }
        - { proto: tcp, ports: 5228, comment: Android and Chrome sync }
       # 'allow' can also be 'forward' to route the traffic to a single destination host or IP
    # server vlan  has access_vlans=all so no rules needed
    - comment: clients can SSH to servers
      source: 
        # vswitch required when vlan is not 'all' or 'internet'
        vswitch: public
        vlan: client
        # optional ipv4_address, ipv6_address, ipset or hostname to narrow application from the entire vlan
        # if only ipv4 or ipv6 specified, rule will only exist for that version
        # hostname can be from a host YAML, site level external_hosts or vlan level DHCP reservations or static_hosts
        # configured host will use ipv4 and/org ipv6 addresses as defined
      destination:
        vswitch: public
        vlan: server
      allow:
        - ssh
      # client has allow_internet=true so no extra rules needed
